var request = require("request");

var google_DriveapiUrl = 'https://script.google.com/macros/s/AKfycbyZnM23QAHOvMHBTc96Mxi122gtMGnglYDb2PRS2hWZsCkMgks/exec';


var Today = new Date();
var fileName = '40831111_40832222_02'; //Line 用戶 號碼
var fileType = 'video/mp4'; // 不能更改
var date = Today.getFullYear() + '/' + (Today.getMonth() + 1) + '/' + Today.getDate();
var base64Data = 'AAAAGGZ0eXBtcDQyAAAAAG1wNDFpc29tAAAIZ21vb3YAAABsbXZoZAAAAADaree12q3ntQAAXcAAARuZAAEAAAEAAAAAAAAAAAAAAAABAAAAAAAAAAAAAAAAAAAAAQAAAAAAAAAAAAAAAAAAQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAMAAAOYdHJhawAAAFx0a2hkAAAAAdqt57Xaree1AAAAAQAAAAAAARuZAAAAAAAAAAAAAAAAAAAAAAABAAAAAAAAAAAAAAAAAAAAAQAAAAAAAAAAAAAAAAAAQAAAAAPAAAACHAAAAAADNG1kaWEAAAAgbWRoZAAAAADaree12q3ntQAAXcAAARuZVcQAAAAAAC1oZGxyAAAAAAAAAAB2aWRlAAAAAAAAAAAAAAAAVmlkZW9IYW5kbGVyAAAAAt9taW5mAAAAFHZtaGQAAAABAAAAAAAAAAAAAAAkZGluZgAAABxkcmVmAAAAAAAAAAEAAAAMdXJsIAAAAAEAAAKfc3RibAAAAJ9zdHNkAAAAAAAAAAEAAACPYXZjMQAAAAAAAAABAAAAAAAAAAAAAAAAAAAAAAPAAhwASAAAAEgAAAAAAAAAAQpBVkMgQ29kaW5nAAAAAAAAAAAAAAAAAAAAAAAAAAAAABj//wAAADlhdmNDAUJAH//hACEnQkAflaA8BF+8BEAAAAMAQAAADDoQDQAAzw73vg7Q4ZUBAAUozjyAAAAAABhzdHRzAAAAAAAAAAEAAABHAAAD6AAAABhjdHRzAAAAAAAAAAEAAABHAAAGQgAAAExzdHNjAAAAAAAAAAUAAAABAAAABwAAAAEAAAADAAAACAAAAAEAAAAHAAAABwAAAAEAAAAIAAAACAAAAAEAAAAKAAAAAgAAAAEAAAEwc3RzegAAAAAAAAAAAAAARwAADrwAAAI9AAABhAAAAk8AAACBAAAEOQAAAuUAAAL3AAACpQAAA5wAAAQeAAALTwAAAHEAAAEZAAADaQAABJYAAABtAAABdQAAA8QAAATSAAAGTgAAAY8AAADkAAADdQAABTsAAANUAAAIIgAAATUAAACUAAAAjgAAAIsAAAG7AAACxgAABmYAAAGpAAAH7QAAAH0AAASoAAAAegAAAbcAAAWUAAABqgAAB7YAAAGxAAAAygAAAMIAAAUuAAABawAACy4AAAXOAAAAlwAAAFcAAAQ4AAAEIAAAC2cAAALAAAAC5wAAAsEAAAKdAAAJFgAAAwEAAAIKAAACPAAAA1oAAAMVAAAC/wAAAvcAAAL/AAAC9wAAAv8AAAL3AAAAOHN0Y28AAAAAAAAACgAACI8AAC7QAABX7AAAgQ8AAKcgAADPcQAA8CwAARvDAAFMqQABbVoAAAAUc3RzcwAAAAAAAAABAAAAAQAAA+10cmFrAAAAXHRraGQAAAAB2q3ntdqt57UAAAACAAAAAAABFqMAAAAAAAAAAAAAAAABAAAAAAEAAAAAAAAAAAAAAAAAAAABAAAAAAAAAAAAAAAAAABAAAAAAAAAAAAAAAAAAAOJbWRpYQAAACBtZGhkAAAAANqt57Xaree1AACsRAACAABVxAAAAAAALWhkbHIAAAAAAAAAAHNvdW4AAAAAAAAAAAAAAABTb3VuZEhhbmRsZXIAAAADNG1pbmYAAAAQc21oZAAAAAAAAAAAAAAAJGRpbmYAAAAcZHJlZgAAAAAAAAABAAAADHVybCAAAAABAAAC+HN0YmwAAABkc3RzZAAAAAAAAAABAAAAVG1wNGEAAAAAAAAAAQA'; // 組員學號

// date = String(date);

function DriveLog() {
  var parameter = {
    fileName: fileName,
    fileType: fileType,
    date: date,
    base64Data: base64Data
  }
  request({
    url: google_DriveapiUrl,
    method: "GET",
    qs: parameter
  }, function(error, response, body) {
    console.log(body);
    // console.log(error);
    // console.log('getO???K');
    // console.log(parameter);
  });
}
DriveLog();







//=================
